"use client";

import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Phone,
  Mail,
  Download,
  Share2,
  Twitter,
  Copy,
  Check,
  ArrowRight,
  Trash2,
  Clock,
  Award,
  Linkedin,
  ChevronDown,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import type { QueueItem } from "@/lib/queue-storage";

// =============================================================================
// Types
// =============================================================================

interface SessionSummaryProps {
  items: QueueItem[];
  researchContext: string | null;
  onClearSession: () => void;
  onContinueResearch: () => void;
}

// =============================================================================
// Helper Functions
// =============================================================================

function formatDateTime(isoString: string): { date: string; time: string } {
  const date = new Date(isoString);
  return {
    date: date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    }),
    time: date.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    }),
  };
}

function getOutcomeLabel(outcome?: string): string {
  switch (outcome) {
    case "successful":
      return "Connected";
    case "voicemail":
      return "Voicemail";
    case "no_answer":
      return "No answer";
    case "busy":
      return "Busy";
    case "sent":
      return "Sent";
    default:
      return "Done";
  }
}

function generateTextReport(
  items: QueueItem[],
  researchContext: string | null
): string {
  const contactedItems = items.filter((item) => item.status === "contacted");
  const now = new Date();

  let report = `CIVIC ENGAGEMENT SESSION REPORT
================================
Generated: ${now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })} at ${now.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}

`;

  if (researchContext) {
    report += `TOPIC: ${researchContext}

`;
  }

  report += `SUMMARY
--------
Total Representatives Contacted: ${contactedItems.length}
Calls Made: ${contactedItems.filter((i) => i.contactMethod === "call").length}
Emails Sent: ${contactedItems.filter((i) => i.contactMethod === "email").length}

CONTACT DETAILS
---------------
`;

  contactedItems.forEach((item, index) => {
    const { legislator } = item;
    const title = legislator.chamber === "Senate" ? "Senator" : "Rep.";
    const contactedAt = item.contactedAt ? formatDateTime(item.contactedAt) : null;

    report += `
${index + 1}. ${title} ${legislator.name}
   Party: ${legislator.party === "D" ? "Democrat" : legislator.party === "R" ? "Republican" : "Independent"}
   State: ${legislator.state}${legislator.district ? `, District ${legislator.district}` : ""}
   Method: ${item.contactMethod === "call" ? "Phone Call" : "Email"}
   Outcome: ${getOutcomeLabel(item.contactOutcome)}
   ${contactedAt ? `Contacted: ${contactedAt.date} at ${contactedAt.time}` : ""}
   ${item.notes ? `Notes: ${item.notes}` : ""}
`;
  });

  report += `
================================
Thank you for participating in democracy!

Generated by Legislators Chat
`;

  return report;
}

function generateShareText(count: number, researchContext: string | null): string {
  const topic = researchContext ? ` about ${researchContext}` : "";
  return `I just contacted ${count} representative${count !== 1 ? "s" : ""}${topic}! Your voice matters - make sure yours is heard too. #CivicEngagement #Democracy`;
}

// =============================================================================
// Sub-Components
// =============================================================================

function CelebrationHero({ count }: { count: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="text-center mb-10"
    >
      {/* Award badge */}
      <motion.div
        initial={{ scale: 0, rotate: -10 }}
        animate={{ scale: 1, rotate: 0 }}
        transition={{ type: "spring", duration: 0.6, delay: 0.1 }}
        className="inline-block mb-6"
      >
        <div className="relative">
          {/* Glow effect */}
          <div className="absolute inset-0 bg-gradient-to-br from-copper/30 to-gold/30 rounded-2xl blur-xl" />

          {/* Badge container */}
          <div className="relative bg-gradient-to-br from-copper/10 to-gold/10 rounded-2xl p-6 border border-copper/20">
            <Award className="size-8 text-copper mx-auto" />
          </div>
        </div>
      </motion.div>

      {/* Headline */}
      <motion.h1
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="font-display text-3xl sm:text-4xl font-bold text-foreground mb-3"
      >
        <span className="text-gradient">Well Done</span>
      </motion.h1>

      {/* Subline */}
      <motion.p
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="text-muted-foreground max-w-md mx-auto leading-relaxed"
      >
        You contacted{" "}
        <span className="text-foreground font-semibold">{count} representative{count !== 1 ? "s" : ""}</span>.{" "}
        Every voice matters in our democracy.
      </motion.p>
    </motion.div>
  );
}

function ImpactCard({
  contactedCount,
  callCount,
  emailCount,
  researchContext,
}: {
  contactedCount: number;
  callCount: number;
  emailCount: number;
  researchContext: string | null;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.4 }}
      className="relative mb-8"
    >
      <div className="relative bg-card border border-border rounded-2xl overflow-hidden">
        {/* Subtle gradient overlay */}
        <div className="absolute inset-0 bg-gradient-to-br from-copper/5 via-transparent to-gold/5 pointer-events-none" />

        <div className="relative p-5 sm:p-6">
          {/* Stats row */}
          <div className="flex items-center justify-center gap-8 sm:gap-12">
            {/* Total */}
            <div className="text-center">
              <div className="font-display text-4xl sm:text-5xl font-bold text-gradient mb-1">
                {contactedCount}
              </div>
              <div className="text-xs text-muted-foreground uppercase tracking-wide">
                Contacted
              </div>
            </div>

            {/* Divider */}
            <div className="h-12 w-px bg-border" />

            {/* Breakdown */}
            <div className="flex items-center gap-6">
              {callCount > 0 && (
                <div className="flex items-center gap-2">
                  <div className="size-8 rounded-lg bg-copper/10 flex items-center justify-center">
                    <Phone className="size-4 text-copper" />
                  </div>
                  <div>
                    <div className="text-lg font-semibold text-foreground">{callCount}</div>
                    <div className="text-xs text-muted-foreground">call{callCount !== 1 ? "s" : ""}</div>
                  </div>
                </div>
              )}

              {emailCount > 0 && (
                <div className="flex items-center gap-2">
                  <div className="size-8 rounded-lg bg-teal/10 flex items-center justify-center">
                    <Mail className="size-4 text-teal" />
                  </div>
                  <div>
                    <div className="text-lg font-semibold text-foreground">{emailCount}</div>
                    <div className="text-xs text-muted-foreground">email{emailCount !== 1 ? "s" : ""}</div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Topic */}
          {researchContext && (
            <div className="mt-5 pt-5 border-t border-border">
              <div className="text-xs text-muted-foreground uppercase tracking-wide mb-1">Topic</div>
              <div className="text-sm text-foreground">{researchContext}</div>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}

function ContactTimelineItem({
  item,
  index,
  isLast,
}: {
  item: QueueItem;
  index: number;
  isLast: boolean;
}) {
  const { legislator } = item;
  const title = legislator.chamber === "Senate" ? "Sen." : "Rep.";
  const contactedAt = item.contactedAt ? formatDateTime(item.contactedAt) : null;

  const partyColor = {
    D: "bg-blue-500",
    R: "bg-red-500",
    I: "bg-purple-500",
  }[legislator.party] || "bg-muted-foreground";

  return (
    <motion.div
      initial={{ opacity: 0, x: -10 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: 0.5 + index * 0.05 }}
      className="relative flex gap-4"
    >
      {/* Timeline connector */}
      <div className="flex flex-col items-center">
        <div
          className={cn(
            "size-2.5 rounded-full ring-4 ring-background",
            item.contactMethod === "call" ? "bg-copper" : "bg-teal"
          )}
        />
        {!isLast && (
          <div className="w-px flex-1 bg-border mt-2" />
        )}
      </div>

      {/* Content */}
      <div className={cn("flex-1 pb-6", isLast && "pb-0")}>
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-medium text-foreground">
                {title} {legislator.name}
              </span>
              <span
                className={cn(
                  "size-1.5 rounded-full",
                  partyColor
                )}
              />
              <span className="text-xs text-muted-foreground">
                {legislator.state}{legislator.district ? `-${legislator.district}` : ""}
              </span>
            </div>

            <div className="flex items-center gap-2 mt-1">
              <span className="text-xs text-muted-foreground">
                {item.contactMethod === "call" ? "Called" : "Emailed"}
              </span>
              <span className="text-muted-foreground/40">·</span>
              <span className="text-xs text-muted-foreground">
                {getOutcomeLabel(item.contactOutcome)}
              </span>
            </div>
          </div>

          {contactedAt && (
            <div className="flex items-center gap-1 text-xs text-muted-foreground flex-shrink-0">
              <Clock className="size-3" />
              {contactedAt.time}
            </div>
          )}
        </div>

        {item.notes && (
          <div className="mt-2 text-xs text-muted-foreground bg-muted/30 rounded-lg px-3 py-2 border border-border/50">
            {item.notes}
          </div>
        )}
      </div>
    </motion.div>
  );
}

function ContactTimeline({ items }: { items: QueueItem[] }) {
  const contactedItems = items.filter((item) => item.status === "contacted");
  const [showAll, setShowAll] = React.useState(false);

  const visibleItems = showAll ? contactedItems : contactedItems.slice(0, 3);
  const hasMore = contactedItems.length > 3;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.5 }}
      className="mb-8"
    >
      <div className="flex items-center justify-between mb-4">
        <h2 className="font-display text-lg font-semibold text-foreground">
          Contact History
        </h2>
        <span className="text-xs text-muted-foreground">
          {contactedItems.length} total
        </span>
      </div>

      <div className="relative bg-card border border-border rounded-xl p-5">
        <AnimatePresence mode="wait">
          <div key={showAll ? "all" : "partial"}>
            {visibleItems.map((item, index) => (
              <ContactTimelineItem
                key={item.legislator.id}
                item={item}
                index={index}
                isLast={index === visibleItems.length - 1}
              />
            ))}
          </div>
        </AnimatePresence>

        {hasMore && (
          <button
            onClick={() => setShowAll(!showAll)}
            className="w-full flex items-center justify-center gap-1 pt-4 mt-4 border-t border-border text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            <span>{showAll ? "Show less" : `Show ${contactedItems.length - 3} more`}</span>
            <ChevronDown className={cn("size-3 transition-transform", showAll && "rotate-180")} />
          </button>
        )}
      </div>
    </motion.div>
  );
}

function ActionButtons({
  shareText,
  onDownload,
  onCopyShare,
  copied,
}: {
  shareText: string;
  onDownload: () => void;
  onCopyShare: () => void;
  copied: boolean;
}) {
  const encodedText = encodeURIComponent(shareText);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.6 }}
      className="flex flex-wrap items-center justify-center gap-3 mb-10"
    >
      <Button onClick={onDownload} variant="outline" size="sm" className="gap-2">
        <Download className="size-4" />
        Download Report
      </Button>

      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            {copied ? (
              <Check className="size-4 text-copper" />
            ) : (
              <Share2 className="size-4" />
            )}
            Share Impact
          </Button>
        </PopoverTrigger>
        <PopoverContent align="center" className="w-72">
          <div className="space-y-4">
            <div>
              <h4 className="font-display font-medium text-sm mb-1">Share your impact</h4>
              <p className="text-xs text-muted-foreground">
                Inspire others to make their voices heard.
              </p>
            </div>

            <div className="flex gap-2">
              <Button
                variant="outline"
                size="icon"
                asChild
                className="hover:bg-sky-500/10 hover:text-sky-500 hover:border-sky-500/50 transition-colors"
              >
                <a
                  href={`https://twitter.com/intent/tweet?text=${encodedText}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Twitter className="size-4" />
                </a>
              </Button>
              <Button
                variant="outline"
                size="icon"
                asChild
                className="hover:bg-blue-500/10 hover:text-blue-500 hover:border-blue-500/50 transition-colors"
              >
                <a
                  href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent("https://legislatorschat.com")}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Linkedin className="size-4" />
                </a>
              </Button>
            </div>

            <div className="pt-3 border-t border-border">
              <p className="text-xs text-muted-foreground mb-2 line-clamp-2">
                {shareText}
              </p>
              <Button variant="secondary" size="sm" onClick={onCopyShare} className="w-full gap-2">
                {copied ? <Check className="size-3" /> : <Copy className="size-3" />}
                {copied ? "Copied!" : "Copy Text"}
              </Button>
            </div>
          </div>
        </PopoverContent>
      </Popover>
    </motion.div>
  );
}

function FooterActions({
  onContinueResearch,
  onClearSession,
}: {
  onContinueResearch: () => void;
  onClearSession: () => void;
}) {
  const [showClearDialog, setShowClearDialog] = React.useState(false);

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
        className="space-y-4"
      >
        {/* Primary action */}
        <Button
          onClick={onContinueResearch}
          size="lg"
          className="w-full gap-2 bg-gradient-to-r from-copper to-gold text-copper-foreground hover:opacity-90"
        >
          Continue Researching
          <ArrowRight className="size-4" />
        </Button>

        {/* Secondary action */}
        <button
          onClick={() => setShowClearDialog(true)}
          className="w-full flex items-center justify-center gap-2 py-2 text-sm text-muted-foreground hover:text-destructive transition-colors"
        >
          <Trash2 className="size-4" />
          Clear session & start fresh
        </button>

        {/* Encouraging footer */}
        <p className="text-center text-xs text-muted-foreground pt-4">
          Democracy thrives when citizens participate.{" "}
          <span className="text-foreground">Thank you.</span>
        </p>
      </motion.div>

      {/* Clear session dialog */}
      <Dialog open={showClearDialog} onOpenChange={setShowClearDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Trash2 className="size-5 text-destructive" />
              Clear Session?
            </DialogTitle>
            <DialogDescription>
              This will clear all your contact history and let you start fresh.
              This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => setShowClearDialog(false)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={() => {
                setShowClearDialog(false);
                onClearSession();
              }}
              className="gap-2"
            >
              <Trash2 className="size-4" />
              Clear Session
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

// =============================================================================
// Main Component
// =============================================================================

export function SessionSummary({
  items,
  researchContext,
  onClearSession,
  onContinueResearch,
}: SessionSummaryProps) {
  const [copied, setCopied] = React.useState(false);

  const contactedItems = items.filter((item) => item.status === "contacted");
  const callCount = contactedItems.filter((i) => i.contactMethod === "call").length;
  const emailCount = contactedItems.filter((i) => i.contactMethod === "email").length;

  const shareText = generateShareText(contactedItems.length, researchContext);

  const handleDownload = () => {
    const report = generateTextReport(items, researchContext);
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `civic-engagement-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyShareText = async () => {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <div className="space-y-2">
      <CelebrationHero count={contactedItems.length} />

      <ImpactCard
        contactedCount={contactedItems.length}
        callCount={callCount}
        emailCount={emailCount}
        researchContext={researchContext}
      />

      <ContactTimeline items={items} />

      <ActionButtons
        shareText={shareText}
        onDownload={handleDownload}
        onCopyShare={handleCopyShareText}
        copied={copied}
      />

      <FooterActions
        onContinueResearch={onContinueResearch}
        onClearSession={onClearSession}
      />
    </div>
  );
}
