"use client";

import * as React from "react";
import { motion } from "framer-motion";
import {
  PartyPopper,
  Phone,
  Mail,
  Download,
  Share2,
  Twitter,
  Facebook,
  Linkedin,
  Copy,
  Check,
  ArrowLeft,
  Trash2,
  MessageCircle,
  Clock,
  Users,
  CheckCircle2,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import type { QueueItem } from "@/lib/queue-storage";
import type { Legislator } from "@/lib/types";

// =============================================================================
// Types
// =============================================================================

interface SessionSummaryProps {
  /** All queue items (to show contacted ones) */
  items: QueueItem[];
  /** Research context/topic */
  researchContext: string | null;
  /** Callback to clear session */
  onClearSession: () => void;
  /** Callback to continue research */
  onContinueResearch: () => void;
}

interface ContactedLegislatorCardProps {
  item: QueueItem;
  index: number;
}

// =============================================================================
// Helper Functions
// =============================================================================

function formatDateTime(isoString: string): { date: string; time: string } {
  const date = new Date(isoString);
  return {
    date: date.toLocaleDateString("en-US", {
      weekday: "short",
      month: "short",
      day: "numeric",
      year: "numeric",
    }),
    time: date.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    }),
  };
}

function getOutcomeLabel(outcome?: string): string {
  switch (outcome) {
    case "successful":
      return "Spoke with someone";
    case "voicemail":
      return "Left voicemail";
    case "no_answer":
      return "No answer";
    case "busy":
      return "Line busy";
    case "sent":
      return "Email sent";
    default:
      return "Contacted";
  }
}

function generateTextReport(
  items: QueueItem[],
  researchContext: string | null
): string {
  const contactedItems = items.filter((item) => item.status === "contacted");
  const now = new Date();

  let report = `CIVIC ENGAGEMENT SESSION REPORT
================================
Generated: ${now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })} at ${now.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true })}

`;

  if (researchContext) {
    report += `TOPIC: ${researchContext}

`;
  }

  report += `SUMMARY
--------
Total Representatives Contacted: ${contactedItems.length}
Calls Made: ${contactedItems.filter((i) => i.contactMethod === "call").length}
Emails Sent: ${contactedItems.filter((i) => i.contactMethod === "email").length}

CONTACT DETAILS
---------------
`;

  contactedItems.forEach((item, index) => {
    const { legislator } = item;
    const title = legislator.chamber === "Senate" ? "Senator" : "Rep.";
    const contactedAt = item.contactedAt ? formatDateTime(item.contactedAt) : null;

    report += `
${index + 1}. ${title} ${legislator.name}
   Party: ${legislator.party === "D" ? "Democrat" : legislator.party === "R" ? "Republican" : "Independent"}
   State: ${legislator.state}${legislator.district ? `, District ${legislator.district}` : ""}
   Method: ${item.contactMethod === "call" ? "Phone Call" : "Email"}
   Outcome: ${getOutcomeLabel(item.contactOutcome)}
   ${contactedAt ? `Contacted: ${contactedAt.date} at ${contactedAt.time}` : ""}
   ${item.notes ? `Notes: ${item.notes}` : ""}
`;
  });

  report += `
================================
Thank you for participating in democracy!

Generated by Legislators Chat
`;

  return report;
}

function generateShareText(count: number, researchContext: string | null): string {
  const topic = researchContext ? ` about ${researchContext}` : "";
  return `I just contacted ${count} representative${count !== 1 ? "s" : ""}${topic}! Your voice matters - make sure yours is heard too. #CivicEngagement #Democracy`;
}

// =============================================================================
// Sub-Components
// =============================================================================

function ContactedLegislatorCard({ item, index }: ContactedLegislatorCardProps) {
  const { legislator } = item;
  const title = legislator.chamber === "Senate" ? "Senator" : "Rep.";
  const contactedAt = item.contactedAt ? formatDateTime(item.contactedAt) : null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
    >
      <Card className="border-green-500/20 bg-green-500/5">
        <CardContent className="pt-4 pb-4">
          <div className="flex items-start gap-3">
            {/* Check icon */}
            <div className="rounded-full bg-green-500/20 p-1.5 mt-0.5">
              <CheckCircle2 className="size-4 text-green-500" />
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="font-medium text-foreground">
                  {title} {legislator.name}
                </span>
                <Badge
                  variant="outline"
                  className={cn(
                    "text-xs",
                    legislator.party === "D"
                      ? "border-blue-500/50 text-blue-500"
                      : legislator.party === "R"
                        ? "border-red-500/50 text-red-500"
                        : "border-purple-500/50 text-purple-500"
                  )}
                >
                  {legislator.party === "D" ? "D" : legislator.party === "R" ? "R" : "I"}
                </Badge>
                <span className="text-xs text-muted-foreground">
                  {legislator.state}
                  {legislator.district ? `-${legislator.district}` : ""}
                </span>
              </div>

              {/* Contact method and outcome */}
              <div className="flex items-center gap-2 mt-2 flex-wrap">
                <Badge
                  variant="secondary"
                  className={cn(
                    "text-xs gap-1",
                    item.contactMethod === "call"
                      ? "bg-amber-500/10 text-amber-500"
                      : "bg-blue-500/10 text-blue-500"
                  )}
                >
                  {item.contactMethod === "call" ? (
                    <Phone className="size-3" />
                  ) : (
                    <Mail className="size-3" />
                  )}
                  {item.contactMethod === "call" ? "Call" : "Email"}
                </Badge>
                <span className="text-xs text-muted-foreground">
                  {getOutcomeLabel(item.contactOutcome)}
                </span>
              </div>

              {/* Timestamp */}
              {contactedAt && (
                <div className="flex items-center gap-1 mt-2 text-xs text-muted-foreground">
                  <Clock className="size-3" />
                  {contactedAt.date} at {contactedAt.time}
                </div>
              )}

              {/* Notes */}
              {item.notes && (
                <div className="mt-2 text-xs text-muted-foreground bg-muted/50 rounded p-2">
                  <span className="font-medium">Notes:</span> {item.notes}
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}

function SharePopover({
  shareText,
  onCopy,
}: {
  shareText: string;
  onCopy: () => void;
}) {
  const encodedText = encodeURIComponent(shareText);

  const shareLinks = [
    {
      name: "Twitter / X",
      icon: Twitter,
      url: `https://twitter.com/intent/tweet?text=${encodedText}`,
      color: "hover:text-sky-400",
    },
    {
      name: "Facebook",
      icon: Facebook,
      url: `https://www.facebook.com/sharer/sharer.php?quote=${encodedText}`,
      color: "hover:text-blue-600",
    },
    {
      name: "LinkedIn",
      icon: Linkedin,
      url: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent("https://legislatorschat.com")}&summary=${encodedText}`,
      color: "hover:text-blue-500",
    },
  ];

  return (
    <PopoverContent align="end" className="w-64">
      <div className="space-y-3">
        <div>
          <h4 className="font-medium text-sm mb-1">Share your impact</h4>
          <p className="text-xs text-muted-foreground">
            Inspire others to participate in democracy!
          </p>
        </div>

        {/* Social links */}
        <div className="flex gap-2">
          {shareLinks.map(({ name, icon: Icon, url, color }) => (
            <Button
              key={name}
              variant="outline"
              size="icon"
              asChild
              className={cn("transition-colors", color)}
            >
              <a href={url} target="_blank" rel="noopener noreferrer" title={name}>
                <Icon className="size-4" />
              </a>
            </Button>
          ))}
        </div>

        {/* Copy text button */}
        <div className="pt-2 border-t border-border">
          <p className="text-xs text-muted-foreground mb-2 line-clamp-2">
            {shareText}
          </p>
          <Button variant="outline" size="sm" onClick={onCopy} className="w-full gap-1.5">
            <Copy className="size-3" />
            Copy Text
          </Button>
        </div>
      </div>
    </PopoverContent>
  );
}

function ClearSessionDialog({
  open,
  onOpenChange,
  onConfirm,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onConfirm: () => void;
}) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Trash2 className="size-5 text-destructive" />
            Clear Session?
          </DialogTitle>
          <DialogDescription>
            This will clear all your contact history and let you start fresh. This action
            cannot be undone.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button variant="destructive" onClick={onConfirm} className="gap-1.5">
            <Trash2 className="size-4" />
            Clear Session
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// =============================================================================
// Main Component
// =============================================================================

export function SessionSummary({
  items,
  researchContext,
  onClearSession,
  onContinueResearch,
}: SessionSummaryProps) {
  const [showClearDialog, setShowClearDialog] = React.useState(false);
  const [copied, setCopied] = React.useState(false);

  const contactedItems = items.filter((item) => item.status === "contacted");
  const callCount = contactedItems.filter((i) => i.contactMethod === "call").length;
  const emailCount = contactedItems.filter((i) => i.contactMethod === "email").length;

  const shareText = generateShareText(contactedItems.length, researchContext);

  const handleDownload = () => {
    const report = generateTextReport(items, researchContext);
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `civic-engagement-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyShareText = async () => {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleClearConfirm = () => {
    setShowClearDialog(false);
    onClearSession();
  };

  return (
    <div className="space-y-6">
      {/* Hero section */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center py-8"
      >
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", duration: 0.5 }}
          className="inline-flex items-center justify-center rounded-full bg-green-500/20 p-4 mb-4"
        >
          <PartyPopper className="size-8 text-green-500" />
        </motion.div>
        <motion.h2
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="text-2xl font-bold text-foreground mb-2"
        >
          Outstanding Work!
        </motion.h2>
        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="text-muted-foreground max-w-md mx-auto"
        >
          You&apos;ve made your voice heard. Every contact counts in a healthy democracy.
        </motion.p>
      </motion.div>

      {/* Stats cards */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="grid grid-cols-3 gap-4"
      >
        <Card className="text-center">
          <CardContent className="pt-4 pb-4">
            <div className="rounded-full bg-primary/10 p-2 w-fit mx-auto mb-2">
              <Users className="size-5 text-primary" />
            </div>
            <p className="text-2xl font-bold text-foreground">{contactedItems.length}</p>
            <p className="text-xs text-muted-foreground">Contacted</p>
          </CardContent>
        </Card>

        <Card className="text-center">
          <CardContent className="pt-4 pb-4">
            <div className="rounded-full bg-amber-500/10 p-2 w-fit mx-auto mb-2">
              <Phone className="size-5 text-amber-500" />
            </div>
            <p className="text-2xl font-bold text-foreground">{callCount}</p>
            <p className="text-xs text-muted-foreground">Calls</p>
          </CardContent>
        </Card>

        <Card className="text-center">
          <CardContent className="pt-4 pb-4">
            <div className="rounded-full bg-blue-500/10 p-2 w-fit mx-auto mb-2">
              <Mail className="size-5 text-blue-500" />
            </div>
            <p className="text-2xl font-bold text-foreground">{emailCount}</p>
            <p className="text-xs text-muted-foreground">Emails</p>
          </CardContent>
        </Card>
      </motion.div>

      {/* Research topic */}
      {researchContext && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <Card className="bg-muted/30">
            <CardContent className="pt-4 pb-4">
              <div className="flex items-start gap-3">
                <MessageCircle className="size-5 text-muted-foreground mt-0.5" />
                <div>
                  <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
                    Topic
                  </p>
                  <p className="text-sm text-foreground">{researchContext}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Action buttons */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        className="flex flex-wrap gap-2 justify-center"
      >
        <Button onClick={handleDownload} variant="outline" className="gap-1.5">
          <Download className="size-4" />
          Download Report
        </Button>

        <Popover>
          <PopoverTrigger asChild>
            <Button variant="outline" className="gap-1.5">
              {copied ? (
                <Check className="size-4 text-green-500" />
              ) : (
                <Share2 className="size-4" />
              )}
              Share Impact
            </Button>
          </PopoverTrigger>
          <SharePopover shareText={shareText} onCopy={handleCopyShareText} />
        </Popover>
      </motion.div>

      {/* Contacted legislators list */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.7 }}
      >
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <CheckCircle2 className="size-5 text-green-500" />
              Contacted Representatives
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="max-h-[400px] overflow-y-auto pr-1">
              <div className="space-y-3 pr-3">
                {contactedItems.map((item, index) => (
                  <ContactedLegislatorCard
                    key={item.legislator.id}
                    item={item}
                    index={index}
                  />
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Footer actions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.8 }}
        className="flex flex-col sm:flex-row gap-3 pt-4 border-t border-border"
      >
        <Button onClick={onContinueResearch} className="flex-1 gap-1.5">
          <ArrowLeft className="size-4" />
          Continue Research
        </Button>
        <Button
          variant="outline"
          onClick={() => setShowClearDialog(true)}
          className="flex-1 gap-1.5 text-muted-foreground hover:text-destructive hover:border-destructive"
        >
          <Trash2 className="size-4" />
          Clear & Start Fresh
        </Button>
      </motion.div>

      {/* Encouraging message */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1 }}
        className="text-center py-4"
      >
        <p className="text-sm text-muted-foreground">
          Democracy works best when citizens participate.{" "}
          <span className="text-foreground font-medium">Thank you for being engaged!</span>
        </p>
      </motion.div>

      {/* Clear session confirmation dialog */}
      <ClearSessionDialog
        open={showClearDialog}
        onOpenChange={setShowClearDialog}
        onConfirm={handleClearConfirm}
      />
    </div>
  );
}
