import type { Legislator, Document, VoteRecord, Hearing } from "./types";

/**
 * Mock legislator data for testing the filtering UI
 */
export const MOCK_LEGISLATORS: Legislator[] = [
  {
    id: "S000033",
    name: "Bernie Sanders",
    party: "I",
    chamber: "Senate",
    state: "VT",
    stance: "for",
    stanceSummary: "Strong advocate for climate action and renewable energy legislation.",
    contact: {
      phone: "(202) 224-5141",
      email: "senator@sanders.senate.gov",
      website: "https://www.sanders.senate.gov",
      office: "332 Dirksen Senate Office Building",
      socialMedia: {
        twitter: "SenSanders",
      },
    },
    termStart: "2007-01-03",
    nextElection: "2024",
  },
  {
    id: "P000197",
    name: "Nancy Pelosi",
    party: "D",
    chamber: "House",
    state: "CA",
    district: "11",
    stance: "for",
    stanceSummary: "Supports comprehensive climate legislation and green infrastructure investment.",
    contact: {
      phone: "(202) 225-4965",
      email: "sf.nancy@mail.house.gov",
      website: "https://pelosi.house.gov",
      office: "2371 Rayburn House Office Building",
      socialMedia: {
        twitter: "SpeakerPelosi",
      },
    },
    termStart: "1987-06-02",
    nextElection: "2024",
  },
  {
    id: "C001098",
    name: "Ted Cruz",
    party: "R",
    chamber: "Senate",
    state: "TX",
    stance: "against",
    stanceSummary: "Opposes most climate regulations, favors energy independence through fossil fuels.",
    contact: {
      phone: "(202) 224-5922",
      email: "senator@cruz.senate.gov",
      website: "https://www.cruz.senate.gov",
      office: "127A Russell Senate Office Building",
      socialMedia: {
        twitter: "SenTedCruz",
      },
    },
    termStart: "2013-01-03",
    nextElection: "2024",
  },
  {
    id: "O000172",
    name: "Alexandria Ocasio-Cortez",
    party: "D",
    chamber: "House",
    state: "NY",
    district: "14",
    stance: "for",
    stanceSummary: "Lead sponsor of Green New Deal, strong advocate for climate justice.",
    contact: {
      phone: "(202) 225-3965",
      email: "ny14.casework@mail.house.gov",
      website: "https://ocasio-cortez.house.gov",
      office: "229 Cannon House Office Building",
      socialMedia: {
        twitter: "AOC",
      },
    },
    termStart: "2019-01-03",
    nextElection: "2024",
  },
  {
    id: "M000355",
    name: "Mitch McConnell",
    party: "R",
    chamber: "Senate",
    state: "KY",
    stance: "against",
    stanceSummary: "Generally opposes climate legislation that impacts coal industry.",
    contact: {
      phone: "(202) 224-2541",
      email: "senator@mcconnell.senate.gov",
      website: "https://www.mcconnell.senate.gov",
      office: "317 Russell Senate Office Building",
      socialMedia: {
        twitter: "LeaderMcConnell",
      },
    },
    termStart: "1985-01-03",
    nextElection: "2026",
  },
  {
    id: "W000817",
    name: "Elizabeth Warren",
    party: "D",
    chamber: "Senate",
    state: "MA",
    stance: "for",
    stanceSummary: "Supports aggressive climate action and corporate accountability for emissions.",
    contact: {
      phone: "(202) 224-4543",
      email: "senator@warren.senate.gov",
      website: "https://www.warren.senate.gov",
      office: "309 Hart Senate Office Building",
      socialMedia: {
        twitter: "SenWarren",
      },
    },
    termStart: "2013-01-03",
    nextElection: "2024",
  },
  {
    id: "G000359",
    name: "Lindsey Graham",
    party: "R",
    chamber: "Senate",
    state: "SC",
    stance: "mixed",
    stanceSummary: "Has shown some support for nuclear energy as climate solution, mixed on regulations.",
    contact: {
      phone: "(202) 224-5972",
      email: "senator@lgraham.senate.gov",
      website: "https://www.lgraham.senate.gov",
      office: "211 Russell Senate Office Building",
      socialMedia: {
        twitter: "LindseyGrahamSC",
      },
    },
    termStart: "2003-01-07",
    nextElection: "2026",
  },
  {
    id: "S000148",
    name: "Chuck Schumer",
    party: "D",
    chamber: "Senate",
    state: "NY",
    stance: "for",
    stanceSummary: "Majority Leader pushing climate provisions in major legislation.",
    contact: {
      phone: "(202) 224-6542",
      email: "senator@schumer.senate.gov",
      website: "https://www.schumer.senate.gov",
      office: "322 Hart Senate Office Building",
      socialMedia: {
        twitter: "SenSchumer",
      },
    },
    termStart: "1999-01-06",
    nextElection: "2028",
  },
  {
    id: "J000289",
    name: "Jim Jordan",
    party: "R",
    chamber: "House",
    state: "OH",
    district: "4",
    stance: "against",
    stanceSummary: "Skeptical of climate regulations, opposes Green New Deal.",
    contact: {
      phone: "(202) 225-2676",
      email: "oh04.casework@mail.house.gov",
      website: "https://jordan.house.gov",
      office: "2056 Rayburn House Office Building",
      socialMedia: {
        twitter: "Jim_Jordan",
      },
    },
    termStart: "2007-01-04",
    nextElection: "2024",
  },
  {
    id: "K000367",
    name: "Amy Klobuchar",
    party: "D",
    chamber: "Senate",
    state: "MN",
    stance: "for",
    stanceSummary: "Supports clean energy transition and climate infrastructure investment.",
    contact: {
      phone: "(202) 224-3244",
      email: "senator@klobuchar.senate.gov",
      website: "https://www.klobuchar.senate.gov",
      office: "425 Dirksen Senate Office Building",
      socialMedia: {
        twitter: "SenAmyKlobuchar",
      },
    },
    termStart: "2007-01-04",
    nextElection: "2024",
  },
  {
    id: "C001075",
    name: "Bill Cassidy",
    party: "R",
    chamber: "Senate",
    state: "LA",
    stance: "mixed",
    stanceSummary: "Supports some climate adaptation measures, balances with energy industry interests.",
    contact: {
      phone: "(202) 224-5824",
      email: "senator@cassidy.senate.gov",
      website: "https://www.cassidy.senate.gov",
      office: "520 Hart Senate Office Building",
      socialMedia: {
        twitter: "SenBillCassidy",
      },
    },
    termStart: "2015-01-06",
    nextElection: "2026",
  },
  {
    id: "F000062",
    name: "Dianne Feinstein",
    party: "D",
    chamber: "Senate",
    state: "CA",
    stance: "for",
    stanceSummary: "Long-time supporter of environmental protection and climate action.",
    contact: {
      phone: "(202) 224-3841",
      email: "senator@feinstein.senate.gov",
      website: "https://www.feinstein.senate.gov",
      office: "331 Hart Senate Office Building",
      socialMedia: {
        twitter: "SenFeinstein",
      },
    },
    termStart: "1992-11-10",
    nextElection: "2024",
  },
];

/**
 * Mock document data for testing
 */
export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-001",
    type: "bill",
    title: "H.R. 3684 - Infrastructure Investment and Jobs Act",
    date: "2021-11-15",
    summary: "Bipartisan infrastructure law investing in roads, bridges, clean energy, and broadband. Includes $550 billion in new federal spending over five years.",
    url: "https://www.congress.gov/bill/117th-congress/house-bill/3684",
    relevance: 0.95,
  },
  {
    id: "doc-002",
    type: "bill",
    title: "H.R. 5376 - Inflation Reduction Act of 2022",
    date: "2022-08-16",
    summary: "Major climate and energy legislation providing $369 billion for clean energy investments, tax credits for EVs, and Medicare drug price negotiations.",
    url: "https://www.congress.gov/bill/117th-congress/house-bill/5376",
    relevance: 0.92,
  },
  {
    id: "doc-003",
    type: "statement",
    title: "Sen. Sanders Floor Speech on Climate Emergency",
    date: "2023-07-12",
    summary: "Senator Bernie Sanders calls for declaration of climate emergency and outlines $16 trillion Green New Deal proposal.",
    relevance: 0.88,
  },
  {
    id: "doc-004",
    type: "transcript",
    title: "House Energy Committee Markup - Clean Energy Standards",
    date: "2023-03-22",
    summary: "Committee debate on proposed clean electricity standard requiring 80% carbon-free power by 2030.",
    relevance: 0.85,
  },
  {
    id: "doc-005",
    type: "bill",
    title: "S. 2093 - CLEAN Future Act",
    date: "2023-06-28",
    summary: "Comprehensive climate legislation setting economy-wide emissions reduction targets and establishing clean energy standards.",
    url: "https://www.congress.gov/bill/118th-congress/senate-bill/2093",
    relevance: 0.82,
  },
];

/**
 * Mock hearing data for testing
 */
export const MOCK_HEARINGS: Hearing[] = [
  {
    id: "hearing-001",
    title: "The Climate Crisis: Urgent Action Needed",
    date: "2023-09-14",
    committee: "Senate Environment and Public Works Committee",
    summary: "Hearing examining latest climate science and policy options. Featured testimony from NOAA Administrator and climate scientists.",
    witnesses: ["Dr. Jane Lubchenco", "Dr. Michael Mann", "EPA Administrator"],
    relevance: 0.94,
  },
  {
    id: "hearing-002",
    title: "Clean Energy Workforce Development",
    date: "2023-08-03",
    committee: "House Education and the Workforce Committee",
    subcommittee: "Subcommittee on Higher Education and Workforce Development",
    summary: "Examining training programs needed for transition to clean energy economy. Discussed apprenticeship programs and community college partnerships.",
    witnesses: ["Secretary of Energy", "AFL-CIO Representative", "Solar Industry CEO"],
    relevance: 0.87,
  },
  {
    id: "hearing-003",
    title: "Electric Vehicle Infrastructure Deployment",
    date: "2023-07-19",
    committee: "Senate Commerce, Science, and Transportation Committee",
    summary: "Progress update on EV charging network buildout under Infrastructure Investment and Jobs Act.",
    witnesses: ["DOT Secretary", "ChargePoint CEO", "State DOT Officials"],
    videoUrl: "https://www.c-span.org/video/example",
    relevance: 0.83,
  },
  {
    id: "hearing-004",
    title: "Offshore Wind Energy Development",
    date: "2023-06-08",
    committee: "House Natural Resources Committee",
    subcommittee: "Subcommittee on Energy and Mineral Resources",
    summary: "Examination of federal offshore wind leasing program and environmental review processes.",
    witnesses: ["BOEM Director", "Orsted Americas President", "Fishing Industry Representative"],
    relevance: 0.79,
  },
];

/**
 * Mock vote record data for testing
 */
export const MOCK_VOTES: VoteRecord[] = [
  {
    id: "vote-001",
    billId: "H.R.3684",
    billTitle: "Infrastructure Investment and Jobs Act",
    date: "2021-11-05",
    chamber: "House",
    result: "passed",
    yeas: 228,
    nays: 206,
    present: 0,
    notVoting: 1,
    description: "Final passage of bipartisan infrastructure bill.",
    url: "https://clerk.house.gov/Votes/2021369",
    relevance: 0.96,
  },
  {
    id: "vote-002",
    billId: "H.R.5376",
    billTitle: "Inflation Reduction Act of 2022",
    date: "2022-08-12",
    chamber: "Senate",
    result: "passed",
    yeas: 51,
    nays: 50,
    present: 0,
    notVoting: 0,
    description: "Senate passage with Vice President casting tie-breaking vote.",
    url: "https://www.senate.gov/legislative/LIS/roll_call_votes/vote1172/vote_117_2_00325.htm",
    relevance: 0.94,
  },
  {
    id: "vote-003",
    billId: "H.Res.109",
    billTitle: "Green New Deal Resolution",
    date: "2019-03-26",
    chamber: "Senate",
    result: "failed",
    yeas: 0,
    nays: 57,
    present: 43,
    notVoting: 0,
    description: "Procedural vote on Green New Deal resolution. Most Democrats voted 'present' in protest.",
    relevance: 0.89,
  },
  {
    id: "vote-004",
    billId: "S.J.Res.64",
    billTitle: "Congressional Review Act - EPA Methane Rule",
    date: "2021-06-25",
    chamber: "Senate",
    result: "passed",
    yeas: 52,
    nays: 42,
    present: 0,
    notVoting: 6,
    description: "Restored Obama-era methane emissions regulations for oil and gas industry.",
    relevance: 0.85,
  },
  {
    id: "vote-005",
    billId: "H.R.1",
    billTitle: "Energy Innovation and Carbon Dividend Act",
    date: "2023-04-18",
    chamber: "House",
    result: "failed",
    yeas: 195,
    nays: 238,
    present: 0,
    notVoting: 2,
    description: "Carbon fee and dividend proposal failed along mostly party lines.",
    relevance: 0.81,
  },
  {
    id: "vote-006",
    billId: "S.280",
    billTitle: "Nuclear Energy Innovation Act",
    date: "2023-05-11",
    chamber: "Senate",
    result: "passed",
    yeas: 75,
    nays: 20,
    present: 0,
    notVoting: 5,
    description: "Bipartisan support for advanced nuclear reactor development and licensing reform.",
    relevance: 0.78,
  },
];
